# This file is the entry point to configure your own services.
parameters:
    app.salon_email: 'jehaarzitgoed@kapper.nl'
    # Meet-id voor Google Analytics (zie .env)
    google_analytics_id: '%env(GOOGLE_ANALYTICS_ID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\NotificationService:
        arguments:
            $salonEmail: '%app.salon_email%'
